import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend to avoid thread issues in Flask
import matplotlib.pyplot as plt
from keras.models import load_model
from flask import Flask, render_template, request, send_file
import datetime as dt
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
import os
import uuid
import requests

plt.style.use("fivethirtyeight")

app = Flask(__name__)

# Ensure static folder exists
os.makedirs('static', exist_ok=True)

# Load the model
model = load_model('stock_dl_model.h5')

def cleanup_old_charts():
    """Delete old generated chart files to keep static/ folder clean."""
    try:
        for f in os.listdir('static'):
            # Only delete charts and temp csv files generated by requests (having request ID suffix)
            # Do NOT delete the original AAPL_dataset.csv or POWERGRID.NS_dataset.csv files
            if (f.endswith('.png') and ('_' in f)) or (f.endswith('.csv') and ('_dataset_' in f)):
                file_path = os.path.join('static', f)
                if os.path.isfile(file_path):
                    os.remove(file_path)
    except Exception as e:
        print(f"Cleanup error: {e}")

def get_stock_data(stock, start, end):
    """
    Downloads stock data from yfinance. If download fails or is empty (due to rate limiting),
    attempts to load a local fallback CSV dataset from the static folder.
    """
    df = pd.DataFrame()
    
    # Try downloading first
    try:
        print(f"Attempting to download {stock} from yfinance...")
        session = requests.Session()
        session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        })
        df = yf.download(stock, start=start, end=end, session=session)
    except Exception as e:
        print(f"yfinance download exception: {e}")
        
    # If download is empty, check for local fallback files
    if df.empty or len(df) < 150:
        print(f"Download returned no data. Searching for local fallback dataset for {stock}...")
        fallback_paths = [
            f"static/{stock}_dataset.csv",
            f"static/{stock.upper()}_dataset.csv",
            f"{stock.lower()}_dataset.csv",
            "powergrid.csv" if "POWERGRID" in stock.upper() else None
        ]
        # Filter existing paths
        fallback_paths = [p for p in fallback_paths if p and os.path.exists(p)]
        
        if fallback_paths:
            csv_path = fallback_paths[0]
            print(f"Loading local fallback file: {csv_path}")
            try:
                # Try reading with MultiIndex headers first
                df = pd.read_csv(csv_path, header=[0, 1], index_col=0, parse_dates=True)
                if 'Close' not in df.columns.get_level_values(0):
                    # Try single header
                    df = pd.read_csv(csv_path, index_col=0, parse_dates=True)
            except Exception as read_err:
                print(f"Error reading local CSV {csv_path}: {read_err}")
                try:
                    df = pd.read_csv(csv_path, index_col=0, parse_dates=True)
                except Exception:
                    pass
                    
    # Flatten columns if they are MultiIndex
    if not df.empty and isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
        
    return df

@app.route('/', methods=['GET', 'POST'])
def index():
    cleanup_old_charts()
    
    if request.method == 'POST':
        stock = request.form.get('stock', '').strip().upper()
        if not stock:
            stock = 'POWERGRID.NS'
        
        try:
            # Define the start and end dates for stock data
            start = dt.datetime(2000, 1, 1)
            end = dt.datetime(2024, 10, 1)
            
            # Retrieve stock data using robust downloader
            df = get_stock_data(stock, start=start, end=end)
            
            if df.empty or len(df) < 150:
                return render_template('index.html', error=f"No sufficient data found for ticker: '{stock}'. Please check the symbol and try again. (Note: Fallbacks are available for AAPL and POWERGRID.NS)")
            
            # Descriptive Data
            data_desc = df.describe()
            
            # Exponential Moving Averages
            ema20 = df.Close.ewm(span=20, adjust=False).mean()
            ema50 = df.Close.ewm(span=50, adjust=False).mean()
            ema100 = df.Close.ewm(span=100, adjust=False).mean()
            ema200 = df.Close.ewm(span=200, adjust=False).mean()
            
            # Data splitting (70% training, 30% testing)
            train_size = int(len(df) * 0.70)
            data_training = pd.DataFrame(df['Close'][0:train_size])
            data_testing = pd.DataFrame(df['Close'][train_size:len(df)])
            
            # Scaling training data
            scaler = MinMaxScaler(feature_range=(0, 1))
            scaler.fit_transform(data_training)
            
            # Prepare data for prediction
            past_100_days = data_training.tail(100)
            final_df = pd.concat([past_100_days, data_testing], ignore_index=True)
            
            # Re-fit the scaler on final_df to match original notebook training range
            pred_scaler = MinMaxScaler(feature_range=(0, 1))
            input_data = pred_scaler.fit_transform(final_df)
            
            x_test, y_test = [], []
            for i in range(100, input_data.shape[0]):
                x_test.append(input_data[i - 100:i])
                y_test.append(input_data[i, 0])
            x_test, y_test = np.array(x_test), np.array(y_test)
            
            # Make predictions
            y_predicted = model.predict(x_test)
            
            # Correctly inverse transform the predictions and targets to original scales
            y_predicted = pred_scaler.inverse_transform(y_predicted)
            y_test = pred_scaler.inverse_transform(y_test.reshape(-1, 1)).flatten()
            
            # Generate a unique request ID to avoid caching
            req_id = uuid.uuid4().hex[:8]
            
            # Plot 1: Closing Price vs Time Chart with 20 & 50 Days EMA
            fig1, ax1 = plt.subplots(figsize=(12, 6))
            ax1.plot(df.index, df.Close, 'y', label='Closing Price', linewidth=1.5)
            ax1.plot(df.index, ema20, 'g', label='EMA 20', linewidth=1.5)
            ax1.plot(df.index, ema50, 'r', label='EMA 50', linewidth=1.5)
            ax1.set_title(f"{stock} - Closing Price vs Time (20 & 50 Days EMA)")
            ax1.set_xlabel("Time")
            ax1.set_ylabel("Price")
            ax1.legend()
            ema_chart_path = f"static/ema_20_50_{req_id}.png"
            fig1.savefig(ema_chart_path, bbox_inches='tight', facecolor='#1f2328', edgecolor='none')
            plt.close(fig1)
            
            # Plot 2: Closing Price vs Time Chart with 100 & 200 Days EMA
            fig2, ax2 = plt.subplots(figsize=(12, 6))
            ax2.plot(df.index, df.Close, 'y', label='Closing Price', linewidth=1.5)
            ax2.plot(df.index, ema100, 'g', label='EMA 100', linewidth=1.5)
            ax2.plot(df.index, ema200, 'r', label='EMA 200', linewidth=1.5)
            ax2.set_title(f"{stock} - Closing Price vs Time (100 & 200 Days EMA)")
            ax2.set_xlabel("Time")
            ax2.set_ylabel("Price")
            ax2.legend()
            ema_chart_path_100_200 = f"static/ema_100_200_{req_id}.png"
            fig2.savefig(ema_chart_path_100_200, bbox_inches='tight', facecolor='#1f2328', edgecolor='none')
            plt.close(fig2)
            
            # Plot 3: Prediction vs Original Trend
            fig3, ax3 = plt.subplots(figsize=(12, 6))
            test_dates = df.index[train_size:len(df)]
            min_len = min(len(test_dates), len(y_test), len(y_predicted))
            
            ax3.plot(test_dates[:min_len], y_test[:min_len], 'g', label="Original Price", linewidth=1.5)
            ax3.plot(test_dates[:min_len], y_predicted[:min_len], 'r', label="Predicted Price", linewidth=1.5)
            ax3.set_title(f"{stock} - Prediction vs Original Trend")
            ax3.set_xlabel("Time")
            ax3.set_ylabel("Price")
            ax3.legend()
            prediction_chart_path = f"static/stock_prediction_{req_id}.png"
            fig3.savefig(prediction_chart_path, bbox_inches='tight', facecolor='#1f2328', edgecolor='none')
            plt.close(fig3)
            
            # Save dataset as CSV
            csv_file_path = f"static/{stock}_dataset_{req_id}.csv"
            df.to_csv(csv_file_path)
            
            # Get last price
            last_val = df['Close'].iloc[-1]
            if hasattr(last_val, 'item'):
                last_val = last_val.item()
            elif isinstance(last_val, (pd.Series, np.ndarray)):
                last_val = last_val[0]
            
            # Get stock metadata for UI info
            stock_info = {
                'ticker': stock,
                'last_price': round(float(last_val), 2),
                'currency': 'USD' if not stock.endswith('.NS') else 'INR'
            }
            
            return render_template('index.html', 
                                   plot_path_ema_20_50=ema_chart_path, 
                                   plot_path_ema_100_200=ema_chart_path_100_200, 
                                   plot_path_prediction=prediction_chart_path, 
                                   data_desc=data_desc.to_html(classes='table table-dark table-hover table-striped table-bordered m-0'),
                                   dataset_link=csv_file_path,
                                   stock_info=stock_info)
        
        except Exception as e:
            import traceback
            traceback.print_exc()
            return render_template('index.html', error=f"An error occurred during prediction: {str(e)}")
            
    return render_template('index.html')

@app.route('/download/<filename>')
def download_file(filename):
    clean_filename = os.path.basename(filename)
    return send_file(os.path.join("static", clean_filename), as_attachment=True)

if __name__ == '__main__':
    app.run(debug=True)
